redis:
  dialtimeout: 500000000
  readtimeout: 30000000
  writetimeout: 30000000
  poolsize: 30
  minIdleConns: 10
  address:
    default:
#      r-2ze7f1da1fd5deb4.redis.rds.aliyuncs.com:6379/1 gtA4BWZ8rWN8SpZkfWZR
      127.0.0.1:6379/1
mysql:
  user: "root"
  password: "root"
  host: "127.0.0.1"
  port: 3306
  maxopenconns: 200
  maxidleconns: 100
