redis:
  dialtimeout: 500000000
  readtimeout: 60000000
  writetimeout: 60000000
  poolsize: 30
  minIdleConns: 10
  address:
    default:
      127.0.0.1:6379/1
mysql:
  user: "root"
  password: "root"
  host: "127.0.0.1"
  port: 3306
  database: yinyu_dev
  maxopenconns: 200
  maxidleconns: 100
